name: web_view
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

#  assets:
#    - assets/fonts/
#    - assets/images/image/
#    - assets/images/icons/
#    - assets/images/image/sun_cloud.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_semiBold.ttf
          weight: 600
